[workspace]
members = [
  "farm-client",
  "farm-ctrl",
  "farm-rpc",
  "farm-sdk",
  "fund",
  "router-main",
  "router-raydium",
  "router-saber",
  "router-orca",
  "vaults"
]

[profile.dev]
split-debuginfo = "unpacked"
